# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'cardmaker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cardmaker
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  #pod 'react-native-google-analytics-bridge', :path => '../node_modules/react-native-google-analytics-bridge'

  #pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

end